"""
evaluate.py
-----------
Runs the trained model on the held-out test split and reports real
accuracy, per-class precision/recall/F1, and a confusion matrix.

No numbers in this script are hardcoded — everything is computed from the
actual model predictions on the actual test set at runtime, and written to
RESULTS.md so results can't be accidentally fabricated or stale.

Usage:
    python src/evaluate.py --checkpoint models/best_model.pth
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from torch.utils.data import DataLoader

from dataset import DefectDataset
from model import build_model
from preprocessing import get_eval_transforms


@torch.no_grad()
def get_predictions(model, loader, device):
    model.eval()
    all_preds, all_labels, all_probs = [], [], []
    for images, labels in loader:
        images = images.to(device)
        outputs = model(images)
        probs = torch.softmax(outputs, dim=1)
        preds = probs.argmax(dim=1).cpu().numpy()

        all_preds.extend(preds)
        all_labels.extend(labels.numpy())
        all_probs.extend(probs.cpu().numpy())
    return np.array(all_labels), np.array(all_preds), np.array(all_probs)


def plot_confusion_matrix(cm: np.ndarray, classes: list[str], out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(8, 7))
    im = ax.imshow(cm, cmap="Blues")
    ax.set_xticks(range(len(classes)))
    ax.set_yticks(range(len(classes)))
    ax.set_xticklabels(classes, rotation=45, ha="right")
    ax.set_yticklabels(classes)
    ax.set_xlabel("Predicted label")
    ax.set_ylabel("True label")
    ax.set_title("Confusion Matrix — Test Set")

    thresh = cm.max() / 2.0
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(
                j, i, format(cm[i, j], "d"),
                ha="center", va="center",
                color="white" if cm[i, j] > thresh else "black",
            )
    fig.colorbar(im, ax=ax)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description="Evaluate defect classifier on the test set")
    parser.add_argument("--checkpoint", default="models/best_model.pth")
    parser.add_argument("--data-dir", default="data/processed")
    parser.add_argument("--models-dir", default="models")
    parser.add_argument("--batch-size", type=int, default=32)
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    ckpt = torch.load(args.checkpoint, map_location=device)
    classes = ckpt["classes"]

    model = build_model(num_classes=len(classes))
    model.load_state_dict(ckpt["model_state_dict"])
    model.to(device)

    test_ds = DefectDataset(Path(args.data_dir), "test", classes=classes, transform=get_eval_transforms())
    test_loader = DataLoader(test_ds, batch_size=args.batch_size, shuffle=False)
    print(f"Test samples: {len(test_ds)}")

    y_true, y_pred, y_probs = get_predictions(model, test_loader, device)

    acc = accuracy_score(y_true, y_pred)
    report = classification_report(y_true, y_pred, target_names=classes, digits=4)
    report_dict = classification_report(y_true, y_pred, target_names=classes, digits=4, output_dict=True)
    cm = confusion_matrix(y_true, y_pred)

    print(f"\nOverall Test Accuracy: {acc:.4f}\n")
    print("Classification Report:")
    print(report)
    print("Confusion Matrix:")
    print(cm)

    models_dir = Path(args.models_dir)
    plot_confusion_matrix(cm, classes, models_dir / "confusion_matrix.png")

    # Write real results to RESULTS.md (not fabricated — pulled straight
    # from the sklearn outputs computed above).
    lines = [
        "# Evaluation Results (auto-generated by evaluate.py)\n",
        f"**Checkpoint:** `{args.checkpoint}`  \n",
        f"**Test samples:** {len(test_ds)}  \n",
        f"**Overall Accuracy:** {acc:.4f}\n",
        "\n## Per-class metrics\n",
        "| Class | Precision | Recall | F1-score | Support |",
        "|---|---|---|---|---|",
    ]
    for cls in classes:
        m = report_dict[cls]
        lines.append(f"| {cls} | {m['precision']:.4f} | {m['recall']:.4f} | {m['f1-score']:.4f} | {int(m['support'])} |")
    lines.append(f"\n**Macro F1:** {report_dict['macro avg']['f1-score']:.4f}")
    lines.append(f"\n**Weighted F1:** {report_dict['weighted avg']['f1-score']:.4f}")
    lines.append("\n\nConfusion matrix image: `models/confusion_matrix.png`\n")

    with open("RESULTS.md", "w") as f:
        f.write("\n".join(lines))
    print("\nResults written to RESULTS.md and models/confusion_matrix.png")


if __name__ == "__main__":
    main()
